### PR TITLE
Fix Next.js warning for image loader

### LINKED ISSUE #50: Image with src has a "loader" property that does not implement width. Please implement it or use the "unoptimized" property instead.
Seems that the loader property is not optimized.

[Next.js](https://nextjs.org/docs/messages/next-image-missing-loader-width)

### PR DESCRIPTION
**Pull request by andershagbard**
Resolves #50 

[Quality for Sanity CDN is 75 per default](https://www.sanity.io/docs/image-urls#q-83311ae15535).

### CODE REVIEW

**Comment by lorenzodejong** [comment]
Could you elaborate on what this change does specifically, and how it solved the image loader issue?

**Comment by andershagbard** [comment]
Next.js has a check to ensure that the loader uses it's properties. Therefore the warning.

https://github.com/vercel/next.js/blob/00ed837bb4b71ce0c30256e4d07638225b31a7e5/packages/next/src/shared/lib/get-img-props.ts#L529

**Comment by lorenzodejong** [comment]
@andershagbard based on the linked source code from Next.js, I don't see how this would solve the explicit issue triggering the error indicating the loader does not implement the width.

Could you elaborate on the specific fix you're introducing here and how it relates to the code path you linked in the Next.js Image source code?

**Comment by andershagbard** [comment]
Found the actual issue.

Closed in favor of: https://github.com/lorenzodejong/next-sanity-image/pull/68

**Pull request closed without merging**
